### ISSUE TITLE
Роза

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/BOOMERANG-2#12]
1. Создать противника, стреляющего лазером
2. Лазер строго вертикальный или горизонтальный, является линией толщиной в три пикселя, которая идет от розы до первого препятствия (стены на глобальной карте)
3. Направление лазера зависит от направления розы. Роза никуда не поворачивается и не двигается
4. Лазер появляется мгновенно по всей вертикали (горизонтали)

5. У розы есть два состояния: включена и выключена. в выключенном состоянии роза переходит в "сплюснутый" вид. При включенном -- выпускает лазер.

6. Помимо противника, создать отдельный модуль с методами Game, в котором противники подписываются на ивенты. (для удобства, чтобы подписывание объектов на ивенты было изолировано)
7. Лазер должен появляться четко в ритм. Но появлению лазера предшествует быстрая анимация "вытягивания" розы. Поэтому запускать анимацию вытягивания нужно на опережение.

![Rose2(1)](https://github.com/VIPigeon/BOOMERANG-2/assets/56171621/80a11af5-a2ab-40ad-b93e-7a830147d2be)

**Comment by kawaii-Code** [comment]
Эта роза так прекрасна...

Я подарю эту розу **тебе** 🥰🥰🥰

**Comment by VIPigeon** [comment]
Небольшие правка к текущему состоянию розы:

1. Сделать розу смертной (по идее, для этого достаточно сделать ее наследником Enemy)
2. Автоматизировать расчет переменной ROSE_ANIMATION_DURATION_MS

**Comment by kawaii-Code** [comment]
Я поправил, поправил я!! 🤗🤗
