### ISSUE TITLE
Калитка убивает задней стороной

### ISSUE THREAD

**Issue by kawaii-Code** [VIPigeon/BOOMERANG-2#15]
Наверное логично, что калитка должна убивать только когда игрок зажимается, но она ещё и убивает с наружной стороны когда открывается.

Вот как это выглядит: 

1. Калитка открывается
![1](https://github.com/VIPigeon/BOOMERANG-2/assets/108984073/e594e996-a543-48de-9066-aa8db2dc5a92)
2. Игрок телепортируется внутрь и умирает 😥
![2](https://github.com/VIPigeon/BOOMERANG-2/assets/108984073/9fd90c5a-9d29-4f63-b6ae-d50893d93de3)

Я не знаю, нужно это фиксить или нет: по идее в игре нельзя будет подойти к калитке вот так, сбоку с внешней стороны, будут какие-нибудь стены или что-то такое.

**Comment by VIPigeon** [comment]
Я не собираюсь это фиксить

**Comment by kawaii-Code** [comment]
Я тоже :cry:

**Comment by MakimaGorky** [comment]
Не пон 😒
