### ISSUE TITLE
Написать Player

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/BOOMERANG-2#17]
Написать объект игрока, наследника Body
1. Игрок двигается
2. Игрок анимирован, как в main
3. Игрок упирается в твердые тайлы (solid_tiles в Data)

**Comment by VIPigeon** [comment]
Отдельно обращаю внимание, что придется переписать Body:move(dx, dy), потому что сейчас в этом методе игрок упирается в край экрана

**Comment by MakimaGorky** [comment]
Фух, готово 😄 👍 
                    🥇

**Comment by MakimaGorky** [comment]
а я ещё бумеранг сделал 😎👉🥏🥏🥏
