### ISSUE TITLE
Переписать game

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/BOOMERANG-2#18]
1. Переписать Game как статический класс game
2.  game содержит в себе два основных метода update и draw, в котором вызываются одноименные методы соответствующих объектов (https://www.figma.com/file/9mpQD5pJBgXzzcai4TpEGb/game?type=whiteboard&node-id=1-208&t=tWMdcK9PpmKlXwFY-0)
3. Логично, что в качестве параметров game должен содержать в себе все объекты, которые необходимо отрисовать и сделать update

**Comment by kawaii-Code** [comment]
Я это сделал!
