### ISSUE TITLE
Анимация включения Checkpoint

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/BOOMERANG-2#28]
Добавить анимацию включения. Задача на один стакан.

![New Piskel(6)](https://github.com/VIPigeon/BOOMERANG-2/assets/56171621/a137ab4c-eb36-4541-86bd-21b51d65c6e4)

**Comment by VIPigeon** [comment]
Стоит заметить, что чекпоинт считается **включенным** в тот момент, когда его коснулся бумеранг, а не в тот момент, когда закончится анимация

**Comment by kawaii-Code** [comment]
Я не успел за один стакан :sob: :sob:
