### ISSUE TITLE
Рефакторинг Lever

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/BOOMERANG-2#29]
1. Сделать рычаг с возможностью переключения бумерангом
2. Рычаг хранит ссылку на дверь, которую открывает
3. Связь между рычагом и дверью устанавливает "по проводу" при запуске игры
4. Провод меняет свой цвет при переключении рычага
5. Реализация двери не принципиальна, все равно мы будем ее дорабатывать

**Comment by VIPigeon** [comment]
Рефакторинг Lever подразумевает рефакторинг Door

**Comment by kawaii-Code** [comment]
Эта задача выполнена идеально :sunglasses: :sudan: !! Отвечаю за слова :+1:
