### ISSUE TITLE
Каскадная система сохранений

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/BOOMERANG-2#31]
1. Система чекпоинтов работает по принципу стека, реализованного через односвязный список: каждый чекпоинт хранит ссылку на тот, что был включен перед ним
2. В game имеется доступ только к последнему включенному чекпоинту. Когда игрок умирает, он возрождается на нем, а в game записывается следующий в очереди
4. Всего есть три состояния чекпоинта: выключенный, включенный и "только что использованный". Чекпоинт в последнем состоянии всегда не больше одного, и его нельзя включить
5. Только что использованный чекпоинт имеет другой спрайт -- #249
6. Стартовый чекпоинт -- особый. На нем игрок может возрождаться сколько угодно раз (этот чекпоинт все еще никак не отображается)

**Comment by kawaii-Code** [comment]
Фууух, я уж испугался

**Comment by kawaii-Code** [comment]
Готово!!!

kawaii-Code@3730fea982e9b34dfd26fc5a95082434f6844146
