### ISSUE TITLE
Калитка убивает 2

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/BOOMERANG-2#32]
1. Калитка открывается и закрывается переключением рычага
2. Калитка толкает объекты Body
3. Если объект Body защемляет калиткой, то объект умирает
4. Задняя часть калитки должна быть всегда закрыта стеной

**Comment by VIPigeon** [comment]
Правки:
1. Улучшить создание двери, чтобы провод мог подключаться как сверху, так и снизу
2. Добавить ускорение при закрытии и шейк экрана при "столкновении" дверей

**Comment by kawaii-Code** [comment]
Правки:
1. Улучшить создание двери, чтобы провод мог поключаться как сверху, так и снизу
2. Добавить ускорение при закрытии и шейк экрана при "столкновении" дверей

**Comment by MakimaGorky** [comment]
![image](https://github.com/VIPigeon/BOOMERANG-2/assets/114951816/ad691d8f-24ca-434c-973c-e2054f37ff53)
