### ISSUE TITLE
Бумеранг пересекается с кем попало

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/BOOMERANG-2#34]
Когда бумеранг не активен, его хитбокс продолжает существовать и взаимодействовать с окружением. Так быть не должно.

Ощущение, что самы простой способ это исправить -- это выносить хитбокс бумеранга за пределы карты, когда он не активен.

**Comment by kawaii-Code** [comment]
Вынес хитбокс на -1000, -1000 :sunglasses:
