### ISSUE TITLE
Видны тайлы-флаги для спавна врагов в процессе игры 

### ISSUE THREAD

**Issue by MakimaGorky** [VIPigeon/BOOMERANG-2#35]
Уважаемые разработчики!, недавно играл в вашу игру и заметил странный баг. После убийства врагов, которые, стоит отметить, выглядят весьма мило, на их месте остаются бессмертные тайлы, также выглядящие воинственно (видимо, предназначенный для их спавна). 

![image](https://github.com/VIPigeon/BOOMERANG-2/assets/114951816/f5750d73-5489-413a-ba92-55009eba233b)
![image](https://github.com/VIPigeon/BOOMERANG-2/assets/114951816/2289a1ed-55d7-4c6b-b346-15077fa3b3d9)
![image](https://github.com/VIPigeon/BOOMERANG-2/assets/114951816/2b6e17f9-ddf9-4bde-abd0-15d6de1dad85)

Тайлы вызывают большое желание их убить, а нельзя 😄, тем самым нарушается непрерывность геймплея и погружения в атмосферу игры. Данные тайлы ухудшают понимание ситуации на игровом поле и мешают игроку ориентироваться, сам пару раз стрелял в них, вместо врагов!! 😱😱. Жду фикса, но не убирайте эти милые тайлы!! Они классные!!! 😍😍

**Comment by kawaii-Code** [comment]
Хм, не знаю почему так  могло произойти, у меня нет идей, хм... :confused:

**Comment by kawaii-Code** [comment]
Я это фиксанул, но через костыль с невидимыми тайлами. Вместо этого костыля можно хранить таблицу со спавнпойнтами врагов и оттуда брать координаты. Но я так не сделал :sunglasses:

**Comment by kawaii-Code** [comment]
Костыль исправлен
