### ISSUE TITLE
Умоляю замержить в мейн

### ISSUE THREAD

**Issue by kawaii-Code** [VIPigeon/BOOMERANG-2#36]
Меня абсолютно бесит, что каждый раз приходится переделывать картридж: что-то всегда меняется в нём, а замержить эти изменения невозможно и приходится перерисовывать спрайты или переделывать карту. Вообщем плохо!!!

**Comment by VIPigeon** [comment]
Разрешаю оставить только main и music1

**Comment by kawaii-Code** [comment]
:+1:
