### ISSUE TITLE
Стрижка розы

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/BOOMERANG-2#37]
Создать противника -- розу
1. Игрок не может проходить сквозь розу
2. Роза бьет в ритм
3. Лазер розы идет до первого препятствия **на карте**

**Comment by VIPigeon** [comment]
Правки:

1. Исправить хитбокс розы
2. Исправить отрисовку лазера

**Comment by kawaii-Code** [comment]
Я исправлюсь, просто дай мне время :skull:
