### ISSUE TITLE
Пулемет

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/BOOMERANG-2#38]
1. Пулемет представляет собой круг с летящими вокруг него пулями
2. У пулемета 3 настраиваемых параметра: диаметр круга, радиус распределения пуль, количество пуль
3. Пулемет стреляет в игрока (в ритм)
4. Во время выстрела все пули перемещаются на одно деление
5. Пуля летит по касательной из точки игрока
7. Сразу после выстела на месте пули появляется новая с соответствующей анимацией
![New Piskel(7)](https://github.com/VIPigeon/BOOMERANG-2/assets/56171621/9be6a8df-8eaf-4963-80e2-ba3f14aa84eb)
![s](https://github.com/VIPigeon/BOOMERANG-2/assets/56171621/a4f1f83f-d9dc-486e-86a2-b9e5e5eedc03)
![sheeps](https://github.com/VIPigeon/BOOMERANG-2/assets/56171621/5c07dfcc-2c09-4cf5-9c2b-71f4e6162477)

**Comment by kawaii-Code** [comment]
Матрица поворота?! :confused: :confounded:

**Comment by kawaii-Code** [comment]
Ух ты что за диаграма

**Comment by VIPigeon** [comment]
Спрайты тела рисовать не надо, просто рисуете HitCircle

**Comment by VIPigeon** [comment]
Цвет пулемета: ffe091

**Comment by VIPigeon** [comment]
1. Пули вокруг пулемета убивают
2. Пулемет имеет возможность стрелять сколь угодно быстро
