### ISSUE TITLE
Анимация смерти игрока

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/BOOMERANG-2#39]
1. Шляпа и очки игрока медленно падают на 2-3 пикселя
2. Остальные пиксели разлетаются. Реализовать при помощи Bullet
![New Piskel(8)](https://github.com/VIPigeon/BOOMERANG-2/assets/56171621/85eb1c56-b7a2-4479-849e-6576819afd1a)

**Comment by kawaii-Code** [comment]
Так ему, игроку!
