### ISSUE TITLE
Анимация получения урона

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/BOOMERANG-2#40]
Когда бумеранг наносит урон, поверх противника появляются разрезы. Сохраняя общий принцип анимации, вы можете свои "разрезы" или перерисовать существующие
![New Piskel(2)](https://github.com/VIPigeon/BOOMERANG-2/assets/56171621/b7513a56-913e-4656-8d07-35fe5035bbaa)
![New Piskel(10)](https://github.com/VIPigeon/BOOMERANG-2/assets/56171621/625c842a-5d0c-41a5-b0c8-d4b266270c71)
![New Piskel(11)](https://github.com/VIPigeon/BOOMERANG-2/assets/56171621/aaf4bc1a-7b7c-40e2-9984-a7557f4a6a6e)
![New Piskel(3)](https://github.com/VIPigeon/BOOMERANG-2/assets/56171621/92205975-f4f5-469f-9b43-a005f46265c4)

**Comment by VIPigeon** [comment]
Правки:
1. Следы должны появляться в точке со случайном сдвигом
2. Анимации не должны разыгрываться единым набором: пусть появляется случайный или не появляется вовсе (для этого добавить в набор следов пустой спрайт)
**3. Новый след должен появляться каждый кадр**

**Comment by MakimaGorky** [comment]
gotowou 🌞
