### ISSUE TITLE
Одуванчик

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/BOOMERANG-2#46]
Реализовать особую пулю -- одуванчик
1. Одуванчик представляет собой белый круг
2. Реализовать алгоритм "расщепления" круга на пули размером 2х2 пикселя
3. При столкновении с твердым тайлом одуванчик рассыпается на пули, которые летят в разные стороны

**Comment by VIPigeon** [comment]
При пересечении с бумерангом одуванчики взрываются

**Comment by kawaii-Code** [comment]
Окей! 👍
