### ISSUE TITLE
Очки

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/BOOMERANG-2#7]
1. Используйте палитру и спрайты из ветки vcroc
2. Надеть на игрока очки, как показано на рисунке
3. Сделать вид сзади и вид спереди. По нажатию клавиш W и S игрок переключает вид на соответствующий

![sunglasses](https://github.com/VIPigeon/BOOMERANG-2/assets/56171621/15e9df64-a6ff-4ae5-8978-85ad55f574b3)

**Comment by kawaii-Code** [comment]
Ой а я сделал это!!! Ой ой ой я ж сделал это хах...

**Comment by kawaii-Code** [comment]
Забыл закрыть через коммит 😥😥😥
