### ISSUE TITLE
Розы, которые стреляют вниз и вправо не добивают два пикселя

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/BOOMERANG-2#76]
Требуется косметическое изменение
1. Захардкодить дорисовку лазера этих роз
2. Проверить, не сломалось ли что от этого изменения
![s](https://github.com/VIPigeon/BOOMERANG-2/assets/56171621/cab595e2-4ea7-4e19-9d96-d2146b24cb85)

**Comment by kawaii-Code** [comment]
:D

![изображение](https://github.com/VIPigeon/BOOMERANG-2/assets/108984073/97458e16-70a8-4891-8ecf-8b7bc2bd03f5)
