### ISSUE TITLE
Калитка

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/BOOMERANG-2#8]
1. Заменить дверь на калитку
2. При закрытии калитка давит все подряд
3. Калитка закрывается с ускорением (прямо пропорционально). Коэффициент ускорения сделать настраиваемым.
    _Открывается -- с постоянной скоростью._
4. В момент закрытия экран встряхивается.
5. В ветке vcroc можно увидеть, что калитка состоит из четырех одинаковых частей, так что метод draw для двери должен быть перезаписан.
![New Piskel(1)](https://github.com/VIPigeon/BOOMERANG-2/assets/56171621/1893b1fc-c221-46b9-92e8-26a26b74b2fe)

**Comment by kawaii-Code** [comment]
Урааа! @MakimaGorky , ты справишься !!! (o′┏▽┓｀o) 
Тебе осталось только:

- [ ] Заменить дверь на калитку
- [ ] При закрытии калитка давит всё подряд
- [ ] Калитка закрывается с **ускорением** (прямо пропорционально!). Коэффициент **сделать** настраиваемым
- [ ] В момент закрытия экран встряхивается~~
- [ ] В ветке `vcroc` можно увидеть

Не так много! У _тебя_ получится! ^(*￣(oo)￣)^. И помни:

> BOOMERANG RETURNS

**Comment by VIPigeon** [comment]
Правки:
1. доделать ускорение двери
2. Встряску делать **не** надо

**Comment by kawaii-Code** [comment]
Я поправил, поправил я!! 🤗🤗

**Comment by MakimaGorky** [comment]
Дело сделано! 😅😅

- [ ] Ура!!!

**Comment by kawaii-Code** [comment]
Дело сделано! :(
