### ISSUE TITLE
Привязать руки к палке

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/BOOMERANG-2#80]
Сделать так, чтобы руки рисовались вместе с палкой, в зависимости от положения палки
Попробовал сделать это в ветке snowman в :_drawline, но не вышло :-( 

![New Piskel-1 png(5)](https://github.com/VIPigeon/BOOMERANG-2/assets/56171621/894a9db8-1f55-4d17-9140-bff1d912b7f6)

**Comment by kawaii-Code** [comment]
O NEEEEET GOSPODI NET

**Comment by kawaii-Code** [comment]
😢 😭 😭

**Comment by kawaii-Code** [comment]
+1
