### ISSUE TITLE
Bike

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/BOOMERANG-2#96]
Реализовать спрайт конца игры.

1. При пересечении с игроком игра заканчивается
2. Реализовать анимацию покоя байка. Байк должен выбрасывать маленькие звездочки, как флаг в Baba is you. Только вместо звездочек байк выбрасывает пиксели
![babIsYou](https://github.com/VIPigeon/BOOMERANG-2/assets/56171621/efb13262-b17b-4240-af13-3c0ac53e1067)

**Comment by VIPigeon** [comment]
При достижении байка игрок садится на байк (тайл 2x2 в ветке bike), о остальная игра останавливается. В новой задаче нужно будет сделать кат-сцену

**Comment by MakimaGorky** [comment]
я сделал звездочки, потому что это попроще

**Comment by MakimaGorky** [comment]
и покрасивее
